name = "harder-timeline"
compatibility_date = "2026-04-15"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "harder-timeline"
# Fill in the database_id after running:  npx wrangler d1 create harder-timeline
database_id = "a55f6e93-9931-419d-bc78-7e2d33669f25"
